# .gitlab-ci.yml file

image: node:latest
cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
    - .npm/

stages:
  - validate
  - test
  - build
  - release
  - deploy

.job_rules:
  rules:
    - if: '$CI_COMMIT_TITLE !~ /^chore: release/'

install:
  stage: .pre
  script:
    - npm ci --cache .npm --prefer-offline

lint:
  stage: validate
  extends: .job_rules
  script:
    - npm run lint

unit_test:
  stage: test
  extends: .job_rules
  script:
    - npm test

integration_test:
  stage: test
  extends: .job_rules
  script:
    - echo "Hello Integration-test"
  needs:
    - job: unit_test
      artifacts: false

e2e_test:
  stage: test
  script:
    - echo "Hello E2E-test"
  needs:
    - job: integration_test
      artifacts: false
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

only_canary:
  stage: validate
  script:
    - echo "Canary"
  rules:
    - if: '$ENV_TARGET == "canary"'
      when: always

release:
  stage: release
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_COMMIT_TAG == null && $CI_COMMIT_TITLE !~ /^chore: release/'
  before_script:
    - git config user.email "$GITLAB_USER_EMAIL"
    - git config user.name "$GITLAB_USER_NAME"
    - git remote set-url origin "$CI_REPOSITORY_URL"
    - git checkout "$CI_COMMIT_BRANCH"
    - npm ci --cache .npm --prefer-offline
  script:
    - npx --yes release-it --ci