name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install
        run: npm ci --cache .npm --prefer-offline

      - name: Validate
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build for production
        run: npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: web
          path: ./dist
